backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"   # where images are stored in repo
public_folder: "/uploads"        # how your site will reference them

collections:
  - name: "blog"
    label: "Blog"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Cover image", name: "image", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
